# Generated by Django 3.2 on 2021-04-20 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendemailapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='groups',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
