# Generated by Django 3.2 on 2021-04-20 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendemailapp', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='patients',
        ),
        migrations.DeleteModel(
            name='AddPatient',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
